### ISSUE TITLE
Relative paths in snippets do not show up in preview

### ISSUE THREAD

**Issue by geverit4** [AdobeDocs/adobe-markdown-authoring#10]
A relative image path inside a snippet does not render the same as the relative path specified directly.  
![Screenshot 2022-08-15 at 12 02 40 PM](https://user-images.githubusercontent.com/1187616/184671657-4036a036-f385-4e2c-8e7a-c1c2564b7406.png)

**Comment by bbringhu** [comment]
I'm still seeing broken image links in preview when there is a root relative link ( `(/help/main-guide/admin/assets/image.png)` ) instead of a relative link ( `(assets/image.png)` ).

**Comment by bbringhu** [comment]
I think this is working now in 2.0.7 but I want to test some more.

**Comment by bbringhu** [comment]
Confirmed fixed
