### ISSUE TITLE
Preview for Adobe Markdown plugin not displaying

### ISSUE THREAD

**Issue by alvawb** [AdobeDocs/adobe-markdown-authoring#17]
In VSC, I'm no longer seeing a preview button for the Adobe Markdown plugin. I have tried uninstalling and reinstalling the plug in from VSC. (I also seem to have 2 of everything but that might be another issue entirely) Per our conversation - @bbringhu 
![Screen Shot 2023-02-16 at 13 58 25](https://user-images.githubusercontent.com/48216938/219461986-e0c96df4-219b-4bdf-b0fe-13b8f3083cba.png)

**Comment by alvawb** [comment]
_

**Comment by alvawb** [comment]
sorry, I removed a comment and it closed

**Comment by geverit4** [comment]
@alvawb: I may be missing something. It looks like you do have the preview icon in your editor. 
![Screenshot 2023-02-19 at 8 04 44 PM](https://user-images.githubusercontent.com/1187616/219987384-c10b3155-78a5-4098-a8b6-a134e8c7dc26.png)

**Comment by sagarKss** [comment]
I have installed the required Markdown extensions:
![image](https://user-images.githubusercontent.com/126975132/223354347-319b41a5-e4cf-4c94-8d20-66e89aa58737.png)

However, I'm not getting the Preview icon. 

On investigating further on a different system, I noticed that my system isn't showing the settings for Markdown, which are available on the system where the Preview icon is showing:
This is what I found on the system where the Preview icon is present:
![image](https://user-images.githubusercontent.com/126975132/223354633-c79d8c6d-feb5-435f-ba84-34db7f8f18f3.png)

This is missing on my system:
![image](https://user-images.githubusercontent.com/126975132/223354685-35e099e1-923d-44e7-83ef-1ebbc2e88841.png)

Please suggest how can I get these settings on my system, or any way to resolve this issue.

**Comment by dshevtsov** [comment]
Preview stopped working in my VSC after disabling and enabling the plugin. I tried reinstalling the plugin but it didn't help.

**Comment by bbringhu** [comment]
Closing this issue with new release. Please re-open if this is still a problem.

**Comment by dshevtsov** [comment]
Still doesn't work for me.
I use v2.1.0 of the extension.

**Comment by dshevtsov** [comment]
Though I can see the preview button. My issue is that the rendering doesn't resolve the special ExL formatting.
Should I open a separate issue for this?

**Comment by bbringhu** [comment]
> Though I can see the preview button. My issue is that the rendering doesn't resolve the special ExL formatting. Should I open a separate issue for this?

Yes, please.

**Comment by dshevtsov** [comment]
https://github.com/AdobeDocs/adobe-markdown-authoring/issues/57

**Comment by bbringhu** [comment]
If this issue occurs, @dshevtsov says to make sure that the built-in Markdown Language Features extension is not disabled. See https://github.com/microsoft/vscode/issues/157012.

FYI: @sagarKss @alvawb
