### ISSUE TITLE
Improve note preview

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/adobe-markdown-authoring#30]
**1: Fix spacing**

Admonitions such as notes and tips should have a distinction between double-space and single-space lines. Currently, any double-spaced paragraphs in Notes will not have extra line spacing between them. Example:

```
>[!TIP]
>
>First line
>
>Second line
>Third line
```

Rendered:

![Screenshot 2023-04-17 at 3 36 36 PM](https://user-images.githubusercontent.com/6193209/232625221-19333a4e-dcc5-4705-82b4-d49be6ef36e8.png)

VS Code Preview:

![Screenshot 2023-04-17 at 3 38 50 PM](https://user-images.githubusercontent.com/6193209/232625583-4ee567fc-599f-48f3-a0bd-940aad0cba68.png)

Here's another example:

![tip-rendering](https://user-images.githubusercontent.com/6193209/232624214-2fbcb89e-6a32-428c-acca-123053be4def.png)

**2: Add text of note type**

It would be great if we could add the word "Note" or "Tip" or whatever the admonition type is that is being used to the top of the note preview.

**Comment by geverit4** [comment]
I noticed that the Authoring Guide doesn't render admonitions properly: 

https://experienceleague.adobe.com/docs/contributor/contributor-guide/writing-essentials/markdown.html

![Screenshot 2023-04-27 at 9 02 46 PM](https://user-images.githubusercontent.com/1187616/235029956-88aadf00-7456-43f1-8ac6-4e2054aeb22c.png)

Is it possible to get working examples that I can use for reference?

**Comment by bbringhu** [comment]
Still open

**Comment by bbringhu** [comment]
@geverit4 - The admonition notes don't render properly in the guides for a quirky reason. I created a clean document with all notes rendered properly:

https://experienceleague.adobe.com/docs/data-workbench/using/hidden-test-page.html

**Comment by geverit4** [comment]
Admonitions preview is now working as expected.  

![Screenshot 2023-05-19 at 4 37 19 PM](https://github.com/AdobeDocs/adobe-markdown-authoring/assets/1187616/671ac197-693b-4a23-ba9c-21d13e618884)

**Comment by bbringhu** [comment]
Woot!

**Comment by bbringhu** [comment]
Fixed in 2.0.7
