### ISSUE TITLE
Only the first badge is rendered in preview

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/adobe-markdown-authoring#37]
Only the first inline badge is rendered in preview.

![](https://user-images.githubusercontent.com/6193209/239657520-3e2e5c7d-c10c-4be7-bd8e-a84521d3a02a.png)

**Comment by geverit4** [comment]
Will be addressed in 2.0.8.

![Screenshot 2023-05-22 at 4 19 14 PM](https://github.com/AdobeDocs/adobe-markdown-authoring/assets/1187616/bf2d83a5-e753-4cfa-a0ba-48c92d9c4c2e)

**Comment by bbringhu** [comment]
Fixed in 2.0.8
