### ISSUE TITLE
Basic badge not rendered in preview

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/adobe-markdown-authoring#40]
Regression of a previous issue. Basic badges without parameters fail to render in preview. Example:

![Screenshot 2023-05-23 at 7 49 21 AM](https://github.com/AdobeDocs/adobe-markdown-authoring/assets/6193209/38355fce-6d77-4edb-9c53-1f07ba0f49c2)

**Comment by geverit4** [comment]
Now handles bare badges properly:
![Screenshot 2023-05-30 at 8 49 05 PM](https://github.com/AdobeDocs/adobe-markdown-authoring/assets/1187616/01819abf-ee41-4f61-b464-b6a429ff7042)

**Comment by bbringhu** [comment]
Confirmed in 2.0.9
