### ISSUE TITLE
Snippet display in preview issue

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/adobe-markdown-authoring#41]
In the syntax-style-guide, the include reference failed to render properly:

![Screenshot 2023-05-23 at 7 55 41 AM](https://github.com/AdobeDocs/adobe-markdown-authoring/assets/6193209/e6f29724-3484-4e3f-a901-1de0fccf6a4c)

Let me know if you need more details or the sample files.

**Comment by geverit4** [comment]
This appears to work properly for me: 
![Screenshot 2023-06-02 at 12 49 41 PM](https://github.com/AdobeDocs/adobe-markdown-authoring/assets/1187616/09a1dc0c-6f79-429a-83fc-4fe0db4c7d6e)

**Comment by bbringhu** [comment]
@geverit4 - Is it possible that there's something local on your computer that's not in the plugin? If not, let's close and re-open if the problem recurs in the store version.
