### ISSUE TITLE
Use updated AM009 file

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/adobe-markdown-authoring#42]
@geverit4 - Matt updated the AM009 rule to allow a new parameter in the VIDEO component. If possible, can you please use this updated version? Here's the syntax we need to allow:

`>[!VIDEO](https://video.tv.adobe.com/v/27069/?quality=12&learn=on){transcript=true}`

Here's the zipped version of the JS file:

[am009.js.zip](https://github.com/AdobeDocs/adobe-markdown-authoring/files/11557090/am009.js.zip)

**Comment by geverit4** [comment]
![Screenshot 2023-05-30 at 8 32 31 PM](https://github.com/AdobeDocs/adobe-markdown-authoring/assets/1187616/deb31fff-797e-43a2-8f5f-7aeff3290861)

**Comment by bbringhu** [comment]
Confirmed in 2.0.9
