### ISSUE TITLE
Error message appear while typing Badge syntax with preview window open

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/adobe-markdown-authoring#45]
When typing badge syntax with the preview window open, I see errors appear as soon as I start typing the parameter. 

![errors-while-typing](https://github.com/AdobeDocs/adobe-markdown-authoring/assets/6193209/018a88ff-4710-4a3e-b9d4-bdf0a7dfab87)

**Comment by geverit4** [comment]
@bbringhu could you attach a copy of the syntax-style-guide.md file?  I don't believe I have a raw copy, just the rendered version from the ExL site.

**Comment by bbringhu** [comment]
Here's the syntax-style-guide.md file:

[syntax-style-guide.md](https://github.com/AdobeDocs/adobe-markdown-authoring/files/11619470/syntax-style-guide.md)

**Comment by bbringhu** [comment]
Let's close this and re-open if someone else runs into it. Edge issue at most...
