### ISSUE TITLE
[!ADMIN] note not rendering in preview

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/adobe-markdown-authoring#51]
There seems to be a problem with AM009. In preview, we fail to preview ADMIN, which is correct, but we display ADMINISTRATION, which is not correct.

`>[!ADMINISTRATION]` (previews, but is incorrect and will fail validation)

`>[!ADMIN]` (currently fails to preview, but will render properly as a note, which confusingly says "ADMINISTRATION" when rendered)

Also, the keyboard shortcut is incorrect. It adds ADMINISTRATION (incorrect) instead of ADMIN.

Summary:
* Update validation to flag `>[!ADMINISTRATION]` as an error and not flag `>[!ADMIN]` as an error
* Render `>[!ADMIN]` in preview with "ADMINISTRATION"
* Change the keyboard shortcut to insert `>[!ADMIN]`, not `>[!ADMINISTRATION]`

**Comment by geverit4** [comment]
Does this mean that ADMIN and ADMINISTRATION simply swap functionality?

**Comment by bbringhu** [comment]
Yes, that's correct. The tricky thing is that `ADMIN` is the right markdown syntax, but it should be rendered in preview as "ADMINISTRATION". Using `ADMINISTRATION` syntax should fail validation. 

It's messy (someone else intervened--you know how that goes), which is why I never caught it before.

**Comment by bbringhu** [comment]
Confirmed fixed in 2.0.11
