### ISSUE TITLE
Toggle Note/Tip/etc. selection not working properly

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/adobe-markdown-authoring#56]
In some instances, choosing an admonition such as a NOTE goes haywire. Instead of adding a note, something goes haywire, and all I get is a large selection. This happens frequently, especially when working in a file that has multiple notes. Problem with looking behind?

**Comment by geverit4** [comment]
I cannot reproduce this issue locally. Here is a video of what I tried:

https://github.com/AdobeDocs/adobe-markdown-authoring/assets/1187616/ec7eecdb-2428-4652-9e0c-fc93b3944b6c

**Comment by bbringhu** [comment]
Here's what I see:

https://github.com/AdobeDocs/adobe-markdown-authoring/assets/6193209/277a2574-9b90-4c1d-be3e-a48aa6a80397

**Comment by bbringhu** [comment]
@geverit4 - I can no longer reproduce this with release 2.1.3. Did you do anything to fix it?

**Comment by geverit4** [comment]
Yes.  In fact, there was quite a bit of re-work with the way that the admonitions are handled.  It should be much more robust now.
