### ISSUE TITLE
Badge colors not rendered properly in preview

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/adobe-markdown-authoring#61]
Neutral and Caution badges have different colors in preview than when rendered.

![badge-colors-preview](https://github.com/AdobeDocs/vsc-extensions/assets/6193209/1553ba18-99fa-4244-b817-bb4bee1925a4)

![badge-colors-live](https://github.com/AdobeDocs/vsc-extensions/assets/6193209/702ecbd3-9026-4161-a263-6e66868fc5d5)

https://experienceleague.adobe.com/en/docs/internal-test/test/markdown-extension-issues#badge-colors

**Comment by geverit4** [comment]
Informative, Positive, Negative and Neutral continue to be supported.  However Spectrum has deprecated non-semantic badge types, and for some reason the Caution badge type.  That means we need to have an exception for the Caution badge type. 

![Screenshot 2024-06-13 at 4 34 01 PM](https://github.com/AdobeDocs/adobe-markdown-authoring/assets/1187616/6f03e9e2-a0e9-402c-96f5-74828eac8159)

See the [latest spectrum docs](https://opensource.adobe.com/spectrum-web-components/components/badge/).

**Comment by bbringhu** [comment]
Confirmed fixed in 2.1.3
