### ISSUE TITLE
Image alignment syntax not properly rendered in preview

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/adobe-markdown-authoring#62]
Problem: {align="right"} after image syntax is rendered as text

![align-preview](https://github.com/AdobeDocs/vsc-extensions/assets/6193209/e72ad6a0-8b59-4e4d-82b7-770de1d07e87)

![align-live](https://github.com/AdobeDocs/vsc-extensions/assets/6193209/d1b431ff-d870-4ecc-8990-7ae09a9f1184)

See https://experienceleague.adobe.com/en/docs/internal-test/test/markdown-extension-issues#align-right-rendering

**Comment by bbringhu** [comment]
@geverit4 - I still see this issue in the 2.1.3 release. The `{align="right"}` parameter still shows up in preview.

**Comment by geverit4** [comment]
Confirmed that this is still a problem.  I did not have enough test cases.  Should be fixed shortly.  


![Screenshot 2024-06-26 at 10 19 50 AM](https://github.com/AdobeDocs/adobe-markdown-authoring/assets/1187616/b5e23e0d-64e7-4a62-8680-f605c7aacae8)

**Comment by geverit4** [comment]
Fixed in version 2.1.4.


![Screenshot 2024-06-26 at 5 27 04 PM](https://github.com/AdobeDocs/adobe-markdown-authoring/assets/1187616/c6ff7238-9c43-4527-b5b3-910362f82960)

**Comment by bbringhu** [comment]
@geverit4 - Great. If you make 2.1.4 available to me, I'll test it. And then I think we'll be ready for updating to the store.

**Comment by bbringhu** [comment]
@geverit4 - Fixed in 2.1.4. Thanks!
