### ISSUE TITLE
Badge syntax in inline code rendered at HTML - Preview

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/adobe-markdown-authoring#63]
Problem: Badge syntax inside inline code rendered as HTML

![badge-preview](https://github.com/AdobeDocs/vsc-extensions/assets/6193209/3bab8d1b-0fa5-4e16-a13e-9d341e32ab1a)

![badge-live](https://github.com/AdobeDocs/vsc-extensions/assets/6193209/c137bd31-39a1-422b-b587-38b6d7a60d3a)

See https://experienceleague.adobe.com/en/docs/internal-test/test/markdown-extension-issues#badges-in-inline-code-blocks-rendered-in-html

**Comment by geverit4** [comment]
Working in branch issue_63. 

![Screenshot 2024-06-13 at 7 50 11 AM](https://github.com/AdobeDocs/adobe-markdown-authoring/assets/1187616/11276783-3e23-4403-b5a4-4e06c7c2ba72)

**Comment by bbringhu** [comment]
Fixed in 2.1.3
