### ISSUE TITLE
Support Shade Boxes in preview

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/adobe-markdown-authoring#7]
Shade boxes are now supported. Documentation and examples:

https://experienceleague.adobe.com/docs/authoring-guide-exl/using/markdown/syntax-style-guide.html?lang=en#shade-boxes

Support in preview.

**Comment by geverit4** [comment]
Shadeboxes are fully supported now.  
![Screenshot 2023-02-07 at 7 58 31 PM](https://user-images.githubusercontent.com/1187616/217401642-27db636b-b003-4c4e-bd87-9b39cc9db9fb.png)
